# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:00"
    versioning-strategy: widen
    labels:
      - "npm"
      - "dependencies"
    open-pull-requests-limit: 0
    # Separate sections of the branch name with a hyphen
    pull-request-branch-name:
      separator: "/"
